
name: Deploy

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: docker build -t farhan1995/testharish .
    - run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u "${{secrets.DOCKERHUB_USERNAME}}"  --password-stdin
    - run: docker push farhan1995/testharish
    - run: echo "Deploying to server always" 
